export const students = [
  {
    id: '1',
    class: 'Class 1',
    name: 'Akash Ahmed',
    scores: 'A',
    percentage: '82%',
  },
  {
    id: '2',
    class: 'Class 1',
    name: 'Md Ferdous Hasan ',
    scores: 'A+',
    percentage: '92%',
  },
  {
    id: '3',
    class: 'Class 1',
    name: 'Arindom',
    scores: 'A+',
    percentage: '95%',
  },
  {
    id: '4',
    class: 'Class 1',
    name: 'Obaidul Islam',
    scores: 'A',
    percentage: '88%',
  },
  {
    id: '5',
    class: 'Class 1',
    name: 'Noyon Dey',
    scores: 'A+',
    percentage: '98%',
  },
  {
    id: '6',
    class: 'Class 1',
    name: 'Sabbir Ahamed',
    scores: 'A',
    percentage: '80%',
  },
  {
    id: '7',
    class: 'Class 1',
    name: 'Nabil Islam',
    scores: 'A',
    percentage: '82%',
  },
  {
    id: '8',
    class: 'Class 1',
    name: 'Saad Hassan',
    scores: 'A*',
    percentage: '98%',
  },
  {
    id: '9',
    class: 'Class 1',
    name: 'Ron Islam',
    scores: 'A',
    percentage: '88%',
  },
  {  id:'10',
    class: 'Class 1',
    name: 'Mashrafee',
    scores: 'A+',
    percentage: '94%',
  },
  {
    id: '11',
    class: 'Class 2',
    name: 'Shki Ahmed',
    scores: 'A',
    percentage: '82%',
  },
  {
    id: '12',
    class: 'Class 2',
    name: 'Md Bordous Hasan ',
    scores: 'A+',
    percentage: '92%',
  },
  {  id:'13',
    class: 'Class 2',
    name: 'Arin Choudhury',
    scores: 'A+',
    percentage: '95%',
  },
  {  id:'14',
    class: 'Class 2',
    name: 'Baizeed Islam',
    scores: 'A',
    percentage: '88%',
  },
  {  id:'15',
    class: 'Class 2',
    name: 'Nripen Dey',
    scores: 'A+',
    percentage: '98%',
  },
  {  id:'16',
    class: 'Class 2',
    name: 'Kabir Ahamed',
    scores: 'A',
    percentage: '80%',
  },
  {  id:'17',
    class: 'Class 2',
    name: 'Nabila Ismail',
    scores: 'A',
    percentage: '82%',
  },
  {  id:'18',
    class: 'Class 2',
    name: 'Sakid Hassan',
    scores: 'A+',
    percentage: '98%',
  },
  {  id:'19',
    class: 'Class 2',
    name: 'Rony Ismail',
    scores: 'A',
    percentage: '88%',
  },
  {  id:'20',
    class: 'Class 2',
    name: 'Marufe Chowdhury',
    scores: 'A+',
    percentage: '94%',
  }


]